// lib/generated-docs.mjs — Blueprint B6.5 generated human docs
//
// Regenerates docs/product.md and docs/architecture.md with:
//   - generation header (no timestamp; byte-identical on unchanged repo)
//   - per-section provenance (path:line, claim id, or graph query reference)
//   - clobber safety (typed docs_conflict when a hand-written file lacks the
//     generation marker; falls back to .agent/docs/)
//   - optional README pointer block (idempotent, --no-readme-link opt-out)
//   - START-HERE.md retirement on every successful build

import {
  createHash,
} from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";

export const VERSION = "0.1.0";
const GENERATION_HEADER_PREFIX = "<!-- generated by blueprint";
const MARKER = "<!-- blueprint:docs:start -->";
const END_MARKER = "<!-- blueprint:docs:end -->";
export const DOC_PATHS = Object.freeze({
  product: "docs/product.md",
  architecture: "docs/architecture.md",
});
const FALLBACK_DIR = ".agent/docs";
const START_HERE_PATH = ".agent/START-HERE.md";
// Files excluded from the generation-id input set because they ARE generated
// (or partially generated) by this very emitter. Keeping them out of the hash
// is what makes an unchanged rebuild byte-identical.
const ID_EXCLUDE = new Set(["README.md", DOC_PATHS.product, DOC_PATHS.architecture]);

function readJson(path) {
  if (!existsSync(path)) return null;
  return JSON.parse(readFileSync(path, "utf8"));
}

function sha1Hex(input) {
  return createHash("sha1").update(input).digest("hex");
}

// Stable identifier for the source set: file paths + repo stats, deliberately
// excluding generated/pointer-block paths. Recompute on every generateDocs
// call so an unchanged rebuild yields the same id and byte-identical output.
function stableGenerationId({ repo, files, stats }) {
  const sortedPaths = (files ?? [])
    .map((entry) => entry.path ?? entry)
    .filter((path) => path && !ID_EXCLUDE.has(path))
    .sort()
    .join("\n");
  return sha1Hex(
    [
      repo ?? "",
      sortedPaths,
      String(stats?.files ?? 0),
      String(stats?.docs ?? 0),
      String(stats?.claims ?? 0),
      String(stats?.codeRefs ?? 0),
    ].join("\n"),
  );
}

export function generationHeader(generationId) {
  return `${GENERATION_HEADER_PREFIX} ${VERSION} gen:${generationId} — edit code/docs sources, not this file -->`;
}

export function isGenerated(targetPath) {
  if (!existsSync(targetPath)) return true;
  const text = readFileSync(targetPath, "utf8");
  // The pointer block uses raw HTML comments; the generation header is a
  // single HTML comment with the marker prefix. Match the start of the file
  // (after any BOM) to the marker.
  const firstLine = text.split(/\r?\n/, 1)[0] ?? "";
  return firstLine.startsWith(GENERATION_HEADER_PREFIX);
}

function writeText(path, body) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body.endsWith("\n") ? body : `${body}\n`);
}

// ── Product doc ─────────────────────────────────────────────────────────

function productSections({ repo, claims, map, generationId }) {
  const header = generationHeader(generationId);
  const eligible = (claims ?? []).filter(
    (c) => ["implemented", "partial", "claim"].includes(c.status) && c.text && c.text.length > 0,
  );
  const bySource = new Map();
  for (const c of eligible) {
    if (!bySource.has(c.source)) bySource.set(c.source, []);
    bySource.get(c.source).push(c);
  }
  const sortedSources = [...bySource.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  const capabilityRows = sortedSources.slice(0, 12).map(([path, list]) => {
    const top = list[0];
    return `- **${path}** — ${top.text} _(source: ${top.source}:${top.line})_`;
  });
  const canonical = ["AGENTS.md", "CLAUDE.md", "README.md"];
  const surfaceRows = (map?.nodes ?? [])
    .filter((n) => n.kind === "doc" && canonical.includes(n.path))
    .map((n) => `- \`${n.path}\` _(source: ${n.path}:1)_`)
    .slice(0, 5);
  return [
    header,
    "",
    `# ${repo} — Product Overview`,
    "",
    "Code-grounded description of what this product is and does. Generated from verified doc claims;",
    "audience and positioning statements come **only** from existing repository docs, never invented.",
    "",
    "## Capabilities",
    "",
    "Plain-language features derived from the verified claim inventory. Each row points back to its source.",
    "",
    ...(capabilityRows.length ? capabilityRows : ["- _No verified capability claims yet._"]),
    "",
    "## Entry points",
    "",
    "User-visible surfaces named by the repository docs:",
    "",
    ...(surfaceRows.length ? surfaceRows : ["- _No canonical entry-point docs found._"]),
    "",
    "## Honesty / Gaps",
    "",
    "Items the docs claim but no implementation file references — and the reverse — surface here as",
    "findings. If a flow is named in user-facing copy but absent from the code graph, it is listed",
    "below, not omitted.",
    "",
    "- _See `.agent/stale.json` for the canonical missing-reference list (provenance: .agent/stale.json)._",
    "",
  ].join("\n");
}

// ── Architecture doc ────────────────────────────────────────────────────

function architectureSections({ repo, map, claims, stale, generationId }) {
  const header = generationHeader(generationId);
  const components = (map?.nodes ?? [])
    .filter((n) => n.kind === "doc" || n.kind === "code_ref")
    .slice(0, 40);
  const componentRows = components.map((n) => {
    if (n.kind === "doc") return `- **doc** · \`${n.path}\` _(source: ${n.path}:1)_`;
    return `- **code_ref** · \`${n.path}\` (exists=${n.exists ?? "?"}) _(source: .agent/map.json)_`;
  });
  const missingCount = (stale?.missingReferences ?? []).length;
  const staleClaimsCount = (stale?.staleClaims ?? []).length;
  const flowRows = [
    "| Entry | Path | Status | Provenance |",
    "|---|---|---|---|",
    "| doc → claims | contains edges in `.agent/map.json` | complete | _source: .agent/map.json:edges_ |",
    `| doc → code refs | mentions-code edges in \`.agent/map.json\` | ${missingCount ? `broken (${missingCount} missing)` : "complete"} | _source: .agent/stale.json:missingReferences_ |`,
    `| claim → doc text | scan in \`scripts/blueprint.mjs\` | ${staleClaimsCount ? `partial (${staleClaimsCount} stale)` : "complete"} | _source: scripts/blueprint.mjs:build_ |`,
  ];
  const capabilityRows = [
    "| Capability | Status | Evidence |",
    "|---|---|---|",
    "| document/ADR/plan claims | covered | _source: .agent/map.json:claims_ |",
    "| code symbols | partial (bootstrap substrate) | _source: scripts/blueprint.mjs:286 |",
    "| code relationships | partial (bootstrap substrate) | _source: scripts/blueprint.mjs:286 |",
    "| task retrieval across code+docs | covered (lexical) | _source: scripts/blueprint.mjs:brief |",
    "| semantic retrieval | unsupported | _source: scripts/blueprint.mjs:semanticReadFirstPaths |",
    "| contradiction/staleness arbitration | covered | _source: scripts/blueprint.mjs:classifyStatus |",
  ];
  return [
    header,
    "",
    `# ${repo} — Architecture`,
    "",
    "Technical overview of components, interfaces, classified flow inventory, and capability coverage.",
    "Generated from the deterministic Phase-1 graph and the locked Bootstrap substrate. Sections that",
    "would draw on a structural code graph are explicitly marked `PARTIAL / CODE-FELL-SHORT` until the",
    "B0–B4 graph substrate ships end-to-end on this repository.",
    "",
    "## Components",
    "",
    ...(componentRows.length ? componentRows : ["- _None recorded._"]),
    "",
    "## Flow inventory",
    "",
    "Each entry point traversed through the deterministic graph to its terminal:",
    "",
    ...flowRows,
    "",
    "## Capability coverage",
    "",
    ...capabilityRows,
    "",
    "## Health & Security (loud-partial when graph is missing)",
    "",
    `- Stale claims: **${staleClaimsCount}** _(source: .agent/stale.json:staleClaims)_`,
    `- Missing references: **${missingCount}** _(source: .agent/stale.json:missingReferences)_`,
    "- Structural-graph health, security synthesis, and the Code Graph operational section are backed",
    "  by the B0 selection (`blueprint-static`, 2026-07-12). They are wired here as `PARTIAL / CODE-FELL-SHORT`",
    "  until the structural provider passes B5 consumption proof. _(source: docs/plans/2026-07-10-blueprint-code-graph-visual-explorer-impl.md:283)_",
    "",
    "## Status",
    "",
    `Generated from index signature \`${generationId}\`. Unchanged-repo rebuilds are byte-identical.`,
    "",
  ].join("\n");
}

// ── README pointer ─────────────────────────────────────────────────────

export function maintainReadmePointer(root) {
  const readmePath = join(root, "README.md");
  if (!existsSync(readmePath)) return { mode: "readme_absent" };
  const text = readFileSync(readmePath, "utf8");
  const block = [
    MARKER,
    "## Repository truth docs",
    "- [Product overview](docs/product.md) — what this is and does (generated, code-grounded)",
    "- [Architecture](docs/architecture.md) — components, flows, interfaces (generated, code-grounded)",
    END_MARKER,
  ].join("\n");
  const startIdx = text.indexOf(MARKER);
  const endIdx = startIdx === -1 ? -1 : text.indexOf(END_MARKER, startIdx);
  if (startIdx === -1 || endIdx === -1) {
    // First-time creation: append with a single trailing newline so the file
    // ends canonically. The signature computation strips the block (and the
    // separator newline) before hashing, so adding the block does not perturb
    // the next source signature.
    const next = text.endsWith("\n") ? `${text}\n${block}\n` : `${text}\n${block}\n`;
    writeText(readmePath, next);
    return { mode: "created" };
  }
  const before = text.slice(0, startIdx);
  const afterRaw = text.slice(endIdx + END_MARKER.length);
  const after = afterRaw.startsWith("\n") ? afterRaw : `\n${afterRaw}`;
  const next = `${before}${block}${after}`;
  if (next !== text) writeText(readmePath, next);
  return { mode: "updated" };
}

// ── Orchestrator ───────────────────────────────────────────────────────

export function generateDocs(root, opts = {}) {
  const noReadmeLink = Boolean(opts.noReadmeLink);
  const map = readJson(join(root, ".agent/map.json"));
  if (!map) {
    return { mode: "missing_map", conflicts: [], wrote: [], fallback: [], readme: null };
  }
  const claims = readJson(join(root, ".agent/claims.json")) ?? [];
  const stale = readJson(join(root, ".agent/stale.json")) ?? {
    missingReferences: [],
    staleClaims: [],
  };
  const index = readJson(join(root, ".agent/index.json")) ?? {
    files: [],
    sourceSignature: "no-index",
  };
  // Prefer the graph's generationId when the graph manifest exists — that is
  // the canonical content hash every other artifact (Blueprint manifest,
  // ContextCandidateSet.freshness.revision, ScopeGrantV1.manifestDigest)
  // binds to. Falls back to a file-list+stats hash only when no graph has
  // been generated yet.
  const graphManifest = readJson(join(root, ".agent/graph/manifest.json")) ?? null;
  const graphGenerationId = graphManifest?.generationId ?? null;
  const generationId = graphGenerationId
    ? graphGenerationId.replace(/^sha256:/, "")
    : stableGenerationId({
        repo: map.repo,
        files: index.files ?? [],
        stats: map.stats,
      });
  const inputs = { repo: map.repo, map, claims, stale, generationId };
  const productBody = productSections(inputs);
  const archBody = architectureSections(inputs);
  const targetProduct = join(root, DOC_PATHS.product);
  const targetArch = join(root, DOC_PATHS.architecture);
  const conflicts = [];
  if (!isGenerated(targetProduct)) conflicts.push(DOC_PATHS.product);
  if (!isGenerated(targetArch)) conflicts.push(DOC_PATHS.architecture);
  const result = {
    mode: conflicts.length ? "docs_conflict" : "wrote",
    conflicts,
    wrote: [],
    fallback: [],
    readme: null,
    retired: [],
  };
  if (conflicts.length) {
    const fallbackDir = join(root, FALLBACK_DIR);
    writeText(join(fallbackDir, "product.md"), productBody);
    writeText(join(fallbackDir, "architecture.md"), archBody);
    result.fallback = [DOC_PATHS.product, DOC_PATHS.architecture];
    return result;
  }
  writeText(targetProduct, productBody);
  writeText(targetArch, archBody);
  result.wrote = [DOC_PATHS.product, DOC_PATHS.architecture];
  if (!noReadmeLink) {
    result.readme = maintainReadmePointer(root);
  }
  const startHere = join(root, START_HERE_PATH);
  if (existsSync(startHere)) {
    rmSync(startHere);
    result.retired.push(START_HERE_PATH);
  }
  return result;
}

export const _internal = { productSections, architectureSections };
